version: '3.7'

services:
  proxy:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    command: nginx -g 'daemon off;'
    depends_on:
      - frontend
      - backend
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./apps:/app/apps
      - ./libs:/app/libs
    command: npx nx serve frontend
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./apps:/app/apps
      - ./libs:/app/libs
    command: npx nx serve backend
    depends_on:
      - postgres
      - typesense
  postgres:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dnd-assistant
      - POSTGRES_USER=dnd-assistant
      - POSTGRES_PASSWORD=dnd-assistant
  typesense:
    image: typesense/typesense:0.25.1
    command: "--data-dir /data --api-key=dnd-assistant --enable-cors"
